### ISSUE TITLE
Sandboxed Open Eval

### ISSUE THREAD

**Issue by scragly** [PythonistaGuild/Pythonista-Bot#1]
The bot will need a publicly usable command that can run code in a contained, safe environment.

Umbra had proposed to use Python Discord's [snekbox](https://github.com/python-discord/snekbox) for running Python.

There was discussions on possibly adding the ability to also run C/C++ code in their own respective contained environments also.

**Comment by AbstractUmbra** [comment]
Resolved in 66c729e601c9b2df33e160ab0be84617d098e437.
